version: '2'

services:
  static:
    image: nginx:alpine
    volumes:
      - ./conf:/conf
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - "${DEVENV_WEB_PATH}:/var/www"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-devenv-http.rule=HostRegexp(`{subdomain:[a-z0-9]+}.dev.env`, `dev.env`)"
      - "traefik.http.routers.static-devenv-http.priority=5"
      - "traefik.http.routers.static-devenv-http.tls=false"
      - "traefik.http.routers.static-devenv-https.rule=HostRegexp(`{subdomain:[a-z0-9]+}.dev.env`, `dev.env`)"
      - "traefik.http.routers.static-devenv-https.priority=5"
      - "traefik.http.routers.static-devenv-https.tls=true"
    restart: always
    networks:
      - devenv


  traefik:
    image: traefik
    command: 
      #- "--log.level=DEBUG"
      - "--api=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.constraints=LabelRegex(`devenv.subdomains`,`.+`) || Label(`traefik.enable`,`true`)"
      - "--providers.docker.defaultRule=Host(`{{ replace \",\" \".dev.env`,`\" (or (index .Labels \"devenv.subdomains\") .Name) }}.dev.env`)"
      - "--providers.docker.network=devenv"
      - "--providers.file.filename=/conf/dynamic.toml"
      - "--providers.file.watch=true"
      - "--serversTransport.forwardingTimeouts.dialTimeout=240s"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf:/conf
    labels:
      - "devenv.subdomains=traefik"
      - "traefik.http.routers.traefik-devenv-http.service=api@internal"
      - "traefik.http.routers.traefik-devenv-http.tls=false"
      - "traefik.http.routers.traefik-devenv-http.middlewares=api-http"
      - "traefik.http.routers.traefik-devenv-https.service=api@internal"
      - "traefik.http.routers.traefik-devenv-https.tls=true"
      - "traefik.http.routers.traefik-devenv-https.middlewares=api-https"
      - "traefik.http.middlewares.api-http.headers.customresponseheaders.Access-Control-Allow-Origin=http://dev.env"
      - "traefik.http.middlewares.api-https.headers.customresponseheaders.Access-Control-Allow-Origin=https://dev.env"
    restart: always
    networks:
      - devenv


  dnsmasq:
    image: dnsmasq
    build: dnsmasq/
    ports: 
      - "127.0.0.1:53:53/udp"
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      - devenv


#  whoami:
#    image: containous/whoami
#    labels:
#      - "devenv.subdomains=whoami"
#      - "traefik.http.routers.whoami-devenv-http.tls=false"
#      - "traefik.http.routers.whoami-devenv-https.tls=true"
#    restart: always
#    networks:
#      - devenv


networks: 
  devenv:
    external: true
